services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8888:80"
    networks:
      - app-network

  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: websolution
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
